version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: ai_education_prod
    ports:
      - "8001:8001"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=${DATABASE_URL:-sqlite:///./ai_education.db}
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=43200
      - UPLOADS_DIR=/app/uploads
      - MATERIALS_DIR=/app/uploads/materials
      - PRESENTATIONS_DIR=/app/uploads/presentations
      - FACES_DIR=/app/uploads/faces
      - AUDIO_DIR=/app/uploads/audio
      - SLIDES_DIR=/app/uploads/slides
      - VECTOR_STORES_DIR=/app/vector_stores
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      - GUNICORN_WORKERS=${GUNICORN_WORKERS:-4}
      - DEBUG=False
    volumes:
      - ./uploads:/app/uploads
      - ./vector_stores:/app/vector_stores
      - ./ai_education.db:/app/ai_education.db
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8001/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 8G
        reservations:
          cpus: '2.0'
          memory: 4G

  nginx:
    image: nginx:alpine
    container_name: ai_education_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      # - ./ssl:/etc/nginx/ssl:ro  # Uncomment for SSL
    depends_on:
      - app
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  default:
    name: ai_education_network
